name: BKCommonLib
main: com.bergerkiller.bukkit.common.internal.CommonPlugin
api-version: 1.19
version: ${version}
build: ${build}
authors: [${authors}]
load: STARTUP
description: Is used in all of my plugins to re-use common functions
dependencies:
  - name: Vault
    required: false
  - name: ProtocolLib
    required: false
  - name: WorldEdit
    required: false
  - name: FastAsyncWorldEdit
    required: false
  - name: ViaVersion
    required: false
  - name: LuckPerms
    required: false
  - name: InteractiveBoard
    required: false
  - name: ImageFrame
    required: false
load-after:
  - name: ProtocolLib
dev-url: ${url}
bstats:
  enabled: true
  plugin-id: 18760
preloader:
  hastebinServer: https://paste.traincarts.net
permissions:
  bkcommonlib.debug.variables:
    default: OP
    description: |
      Allows use of the /debugvar command.
      This command is only available when debugging variables are set.
      In normal production builds, this command and permission are unused.
