name: BKCommonLib
main: com.bergerkiller.bukkit.common.internal.CommonPlugin
api-version: 1.13
version: ${project.version}
build: ${project.buildNumber}
authors: [bergerkiller, lenis0012, timstans, bubba1234119, KamikazePlatypus, mg_1999, Friwi]
load: startup
description: Is used in all of my plugins to re-use common functions
softdepend: [Vault, ProtocolLib]
dev-url: ${project.url}
commands:
  commondebug:
    description: Developer debugging commands for changing values
    aliases: [debug]
    usage: /debug [name] [value...]