package com.bergerkiller.bukkit.common.protocol;

import com.bergerkiller.bukkit.common.reflection.classes.PacketFieldClasses.*;

/**
 * Constants for the fields contained in the packets
 */
public class PacketFields {
	public static final NMSPacket DEFAULT = new NMSPacket();
	public static final NMSPacket0KeepAlive KEEP_ALIVE = null; // = new NMSPacket0KeepAlive();
	public static final NMSPacket1Login LOGIN = null; // = new NMSPacket1Login();
	public static final NMSPacket2Handshake HANDSHAKE = null; // = new NMSPacket2Handshake();
	public static final NMSPacket3Chat CHAT = null; // = new NMSPacket3Chat();
	public static final NMSPacket4UpdateTime UPDATE_TIME = null; // = new NMSPacket4UpdateTime();
	public static final NMSPacket5EntityEquipment ENTITY_EQUIPMENT = null; // = new NMSPacket5EntityEquipment();
	public static final NMSPacket6SpawnPosition SPAWN_POSITION = null; // = new NMSPacket6SpawnPosition();
	public static final NMSPacket7UseEntity USE_ENTITY = null; // = new NMSPacket7UseEntity();
	public static final NMSPacket8UpdateHealth UPDATE_HEALTH = null; // = new NMSPacket8UpdateHealth();
	public static final NMSPacket9Respawn RESPAWN = null; // = new NMSPacket9Respawn();
	public static final NMSPacket10Flying FLYING = null; // = new NMSPacket10Flying();
	public static final NMSPacket11PlayerPosition PLAYER_POSITION = null; // = new NMSPacket11PlayerPosition();
	public static final NMSPacket12PlayerLook PLAYER_LOOK = null; // = new NMSPacket12PlayerLook();
	public static final NMSPacket13PlayerLookMove PLAYER_LOOK_MOVE = null; // = new NMSPacket13PlayerLookMove();
	public static final NMSPacket14BlockDig BLOCK_DIG = null; // = new NMSPacket14BlockDig();
	public static final NMSPacket15Place PLACE = null; // = new NMSPacket15Place();
	public static final NMSPacket16BlockItemSwitch BLOCK_ITEM_SWITCH = null; // = new NMSPacket16BlockItemSwitch();
	public static final NMSPacket17EntityLocationAction ENTITY_LOCATION_ACTION = null; // = new NMSPacket17EntityLocationAction();
	public static final NMSPacket18ArmAnimation ARM_ANIMATION = null; // = new NMSPacket18ArmAnimation();
	public static final NMSPacket19EntityAction ENTITY_ACTION = null; // = new NMSPacket19EntityAction();
	public static final NMSPacket20NamedEntitySpawn NAMED_ENTITY_SPAWN = null; // = new NMSPacket20NamedEntitySpawn();
	public static final NMSPacket22Collect COLLECT = null; // = new NMSPacket22Collect();
	public static final NMSPacket23VehicleSpawn VEHICLE_SPAWN = null; // = new NMSPacket23VehicleSpawn();
	public static final NMSPacket24MobSpawn MOB_SPAWN = null; // = new NMSPacket24MobSpawn();
	public static final NMSPacket25EntityPainting ENTITY_PAINTING = null; // = new NMSPacket25EntityPainting();
	public static final NMSPacket26AddExpOrb ADD_EXP_ORB = null; // = new NMSPacket26AddExpOrb();
	public static final NMSPacket27PlayerInput PLAYER_INPUT = null; // = new NMSPacket27PlayerInput();
	public static final NMSPacket28EntityVelocity ENTITY_VELOCITY = null; // = new NMSPacket28EntityVelocity();
	public static final NMSPacket29DestroyEntity DESTROY_ENTITY = null; // = new NMSPacket29DestroyEntity();
	public static final NMSPacket30Entity ENTITY = null; // = new NMSPacket30Entity();
	public static final NMSPacket31RelEntityMove ENTITY_MOVE = null; // = new NMSPacket31RelEntityMove();
	public static final NMSPacket32EntityLook ENTITY_LOOK = null; // = new NMSPacket32EntityLook();
	public static final NMSPacket33RelEntityMoveLook ENTITY_MOVE_LOOK = null; // = new NMSPacket33RelEntityMoveLook();
	public static final NMSPacket34EntityTeleport ENTITY_TELEPORT = null; // = new NMSPacket34EntityTeleport();
	public static final NMSPacket35EntityHeadRotation ENTITY_HEAD_ROTATION = null; // = new NMSPacket35EntityHeadRotation();
	public static final NMSPacket38EntityStatus ENTITY_STATUS = null; // = new NMSPacket38EntityStatus();
	public static final NMSPacket39AttachEntity ATTACH_ENTITY = null; // = new NMSPacket39AttachEntity();
	public static final NMSPacket40EntityMetadata ENTITY_METADATA = null; // = new NMSPacket40EntityMetadata();
	public static final NMSPacket41MobEffect MOB_EFFECT = null; // = new NMSPacket41MobEffect();
	public static final NMSPacket42RemoveMobEffect REMOVE_MOB_EFFECT = null; // = new NMSPacket42RemoveMobEffect();
	public static final NMSPacket43SetExperience SET_EXPERIENCE = null; // = new NMSPacket43SetExperience();
	public static final NMSPacket44UpdateAttributes UPDATE_ATTRIBUTES = null; // = new NMSPacket44UpdateAttributes();
	public static final NMSPacket51MapChunk MAP_CHUNK = null; // = new NMSPacket51MapChunk();
	public static final NMSPacket52MultiBlockChange MULTI_BLOCK_CHANGE = null; // = new NMSPacket52MultiBlockChange();
	public static final NMSPacket53BlockChange BLOCK_CHANGE = null; // = new NMSPacket53BlockChange();
	public static final NMSPacket54PlayNoteBlock PLAY_NOTEBLOCK = null; // = new NMSPacket54PlayNoteBlock();
	public static final NMSPacket55BlockBreakAnimation BLOCK_BREAK_ANIMATION = null; // = new NMSPacket55BlockBreakAnimation();
	public static final NMSPacket56MapChunkBulk MAP_CHUNK_BULK = null; // = new NMSPacket56MapChunkBulk();
	public static final NMSPacket60Explosion EXPLOSION = null; // = new NMSPacket60Explosion();
	public static final NMSPacket61WorldEvent WORLD_EVENT = null; // = new NMSPacket61WorldEvent();
	public static final NMSPacket62NamedSoundEffect NAMED_SOUND_EFFECT = null; // = new NMSPacket62NamedSoundEffect();
	public static final NMSPacket63WorldParticles WORLD_PARTICLES = null; // = new NMSPacket63WorldParticles();
	public static final NMSPacket70Bed BED = null; // = new NMSPacket70Bed();
	public static final NMSPacket71Weather WEATHER = null; // = new NMSPacket71Weather();
	public static final NMSPacket100OpenWindow OPEN_WINDOW = null; // = new NMSPacket100OpenWindow();
	public static final NMSPacket101CloseWindow CLOSE_WINDOW = null; // = new NMSPacket101CloseWindow();
	public static final NMSPacket102WindowClick WINDOW_CLICK = null; // = new NMSPacket102WindowClick();
	public static final NMSPacket103SetSlot SET_SLOT = null; // = new NMSPacket103SetSlot();
	public static final NMSPacket104WindowItems WINDOW_ITEMS = null; // = new NMSPacket104WindowItems();
	public static final NMSPacket105CraftProgressBar PROGRESS_BAR = null; // = new NMSPacket105CraftProgressBar();
	public static final NMSPacket106Transaction TRANSACTION = null; // = new NMSPacket106Transaction();
	public static final NMSPacket107SetCreativeSlot SET_CREATIVE_SLOT = null; // = new NMSPacket107SetCreativeSlot();
	public static final NMSPacket108ButtonClick BUTTON_CLICK = null; // = new NMSPacket108ButtonClick();
	public static final NMSPacket130UpdateSign UPDATE_SIGN = null; // = new NMSPacket130UpdateSign();
	public static final NMSPacket131ItemData ITEM_DATA = null; // = new NMSPacket131ItemData();
	public static final NMSPacket132TileEntityData TILE_ENTITY_DATA = null; // = new NMSPacket132TileEntityData();
	public static final NMSPacket133OpenTileEntity TILE_ENTITY_OPEN = null; // = new NMSPacket133OpenTileEntity();
	public static final NMSPacket200Statistic STATISTIC = null; // = new NMSPacket200Statistic();
	public static final NMSPacket201PlayerInfo PLAYER_INFO = null; // = new NMSPacket201PlayerInfo();
	public static final NMSPacket202Abilities ABILITIES = null; // = new NMSPacket202Abilities();
	public static final NMSPacket203TabComplete TAB_COMPLETE = null; // = new NMSPacket203TabComplete();
	public static final NMSPacket204LocaleAndViewDistance CLIENT_INFO = null; // = new NMSPacket204LocaleAndViewDistance();
	public static final NMSPacket205ClientCommand CLIENT_COMMAND = null; // = new NMSPacket205ClientCommand();
	public static final NMSPacket206SetScoreboardObjective SET_SCOREBOARD_OBJECTIVE = null; // = new NMSPacket206SetScoreboardObjective();
	public static final NMSPacket207SetScoreboardScore SET_SCOREBOARD_SCORE = null; // = new NMSPacket207SetScoreboardScore();
	public static final NMSPacket208SetScoreboardDisplayObjective SET_SCOREBOARD_DISPLAY_OBJECTIVE = null; // = new NMSPacket208SetScoreboardDisplayObjective();
	public static final NMSPacket209SetScoreboardTeam SET_SCOREBOARD_TEAM = null; // = new NMSPacket209SetScoreboardTeam();
	public static final NMSPacket250CustomPayload CUSTOM_PAYLOAD = null; // = new NMSPacket250CustomPayload();
	public static final NMSPacket252KeyResponse KEY_RESPONSE = null; // = new NMSPacket252KeyResponse();
	public static final NMSPacket253KeyRequest KEY_REQUEST = null; // = new NMSPacket253KeyRequest();
	public static final NMSPacket254GetInfo GET_INFO = null; // = new NMSPacket254GetInfo();
	public static final NMSPacket255KickDisconnect DISCONNECT = null; // = new NMSPacket255KickDisconnect();
}
